### ISSUE TITLE
Document how to set up slapdash file structure in own project?

### ISSUE THREAD

**Issue by brylie** [ned2/slapdash#6] opened 2018-10-29 11:06 UTC
The Slapdash project is very nice for getting started quickly. However, it might be useful to document some of the design decisions that went into the project structure. For example, how does the file structure allow callbacks to be separated into their own file? The monolithic file structure of default Dash apps is of shared concern, and [it is particularly difficult to separate out callbacks](https://community.plot.ly/t/callbacks-in-a-separate-file/15034).

**Comment by ned2** [comment] 2018-10-29 12:11
Would having an example callback in the `callbacks.py` file help? since the Dash `app` instance is imported for you already, it's as simple as dropping in your callbacks into the file using the `@app.callback()` decorator.

**Comment by brylie** [comment] 2018-10-30 10:40
Yes, the example would probably help. However, there must be something I am doing wrong with the order of imports, as I cannot get the callbacks to bind to the layout when doing something like this pseudocode:

## app.py
```py
import .layouts

app = Dash()

app.layout = layouts.main_layout
```

## layouts.py
```py
# imports

main_layout = html.Div(id="main-container", children=[...])
```

## callbacks.py
```py
from .app import app

@app.callback()
def do_something():
    pass
```

So, I am really eager to understand some of the underlying reasons your slapdash structure works :-)

**Comment by ned2** [comment] 2018-10-30 13:50
The issue is likely to do with circular imports, which can be hard to diagnose. If the `app` module is the entry point, then it needs to import the `callbacks` module to register them with the app. But then loading the `callbacks` module will immediately try to import the `app` module, which has not yet finished being imported. This is the reason for separating out the `server` module from the `app` module, an idea which I took from the structure of the [Dash docs](https://github.com/plotly/dash-docs), and which I explain better in this [post](https://community.plot.ly/t/splitting-callback-definitions-in-multiple-files/10583/2), which will likely be helpful.

The alternative approach for structuring your apps  that is suggested in the Dash docs looks different, however it has the same underlying feature that avoids the circular import: the entry point (in this case the `index` module, as opposed to `app` in Slapdash) is not the module where you import the Dash `app` instance from. In this case, that module is `app`, making it functionally the same as the `server` module in Slapdash.

This stuff is a little confusing -- I had to work out what was going on all over again for myself just then. Hope that helps!

**Comment by mungojam** [comment] 2018-11-24 17:08
The general approach I have gone for at the moment is to make sure things happen in this order:

1. Dash app created, with no layout
2. Layouts and associated callbacks created
3, Layout assigned to app.layout
3. Server started

3 has to be situated somewhere such that the layout doesn't get imported until the app has been created

**Comment by ned2** [comment] 2018-11-28 12:57
Ah interesting @mungojam, I think we may have converged on the same generalised approach. That's now exactly what I'm doing in `app.py` and the thing that I like about its current layout, is that it makes this ordering fairly explicit.

**Comment by ned2** [comment] 2018-11-28 12:58
Closing this as slapdash now has an example app including callbacks on Page 1. Thanks @brylie, this was a good suggestion.

**Closed** 2018-11-28 12:58 UTC
